export const loginTypes = {
  USER_LOGIN_BEGIN: "USER_LOGIN_BEGIN",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_ERROR: "USER_LOGIN_ERROR",
};

export const registerTypes = {
  USER_REGISTER_BEGIN: "USER_REGISTER_BEGIN",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_ERROR: "USER_REGISTER_ERROR",
};
